// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import NavigationController from "./navigation_controller"
import LogoutController from "./logout_controller"

application.register("hello", HelloController)
application.register("navigation", NavigationController)
application.register("logout", LogoutController)
